/* =============================================================================
   6ThSense Design System — shared behaviour (v1.0)
   Edit THIS file (in 6ThSense-DesignSystem/), then run sync.bat.

   Works as a classic <script> and as a Vite side-effect import. Exposes window.DS:
     DS.renderHeader(el, appId)       shared app header + tool switcher
     DS.renderFooter(el, appId, note) shared footer
     DS.icon(name, {size})            Lucide icon as an SVG string  (size: 'sm' | 'lg' | 'xl')
     DS.hydrateIcons(root)            swaps <i data-icon="name"> for the SVG
     DS.logo(variant)                 6ThSense mark ('default' | 'inverse')
     DS.toast(message, type)          transient feedback  (type: success | error | warning | info)
     DS.confirm(options)  → Promise<boolean>   the only confirmation dialog
     DS.alert(options)    → Promise<void>      the only blocking message dialog
     DS.setLoading(button, isLoading, text)    the only button loading state
     DS.formatBytes(n)
   ========================================================================== */
(function () {
  'use strict';
  if (typeof window === 'undefined' || window.DS) return;

  /* @icons:start (generated by tools/build-icons.mjs — Lucide, ISC license) */
  const ICONS = {
    "upload": "<path d=\"M12 3v12\"/><path d=\"m17 8-5-5-5 5\"/><path d=\"M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4\"/>",
    "download": "<path d=\"M12 15V3\"/><path d=\"M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4\"/><path d=\"m7 10 5 5 5-5\"/>",
    "x": "<path d=\"M18 6 6 18\"/><path d=\"m6 6 12 12\"/>",
    "check": "<path d=\"M20 6 9 17l-5-5\"/>",
    "plus": "<path d=\"M5 12h14\"/><path d=\"M12 5v14\"/>",
    "minus": "<path d=\"M5 12h14\"/>",
    "file": "<path d=\"M6 22a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h8a2.4 2.4 0 0 1 1.704.706l3.588 3.588A2.4 2.4 0 0 1 20 8v12a2 2 0 0 1-2 2z\"/><path d=\"M14 2v5a1 1 0 0 0 1 1h5\"/>",
    "file-text": "<path d=\"M6 22a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h8a2.4 2.4 0 0 1 1.704.706l3.588 3.588A2.4 2.4 0 0 1 20 8v12a2 2 0 0 1-2 2z\"/><path d=\"M14 2v5a1 1 0 0 0 1 1h5\"/><path d=\"M10 9H8\"/><path d=\"M16 13H8\"/><path d=\"M16 17H8\"/>",
    "file-spreadsheet": "<path d=\"M6 22a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h8a2.4 2.4 0 0 1 1.704.706l3.588 3.588A2.4 2.4 0 0 1 20 8v12a2 2 0 0 1-2 2z\"/><path d=\"M14 2v5a1 1 0 0 0 1 1h5\"/><path d=\"M8 13h2\"/><path d=\"M14 13h2\"/><path d=\"M8 17h2\"/><path d=\"M14 17h2\"/>",
    "presentation": "<path d=\"M2 3h20\"/><path d=\"M21 3v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V3\"/><path d=\"m7 21 5-5 5 5\"/>",
    "image": "<rect width=\"18\" height=\"18\" x=\"3\" y=\"3\" rx=\"2\" ry=\"2\"/><circle cx=\"9\" cy=\"9\" r=\"2\"/><path d=\"m21 15-3.086-3.086a2 2 0 0 0-2.828 0L6 21\"/>",
    "images": "<path d=\"m22 11-1.296-1.296a2.4 2.4 0 0 0-3.408 0L11 16\"/><path d=\"M4 8a2 2 0 0 0-2 2v10a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2\"/><circle cx=\"13\" cy=\"7\" r=\"1\" fill=\"currentColor\"/><rect x=\"8\" y=\"2\" width=\"14\" height=\"14\" rx=\"2\"/>",
    "file-archive": "<path d=\"M13.659 22H18a2 2 0 0 0 2-2V8a2.4 2.4 0 0 0-.706-1.706l-3.588-3.588A2.4 2.4 0 0 0 14 2H6a2 2 0 0 0-2 2v11.5\"/><path d=\"M14 2v5a1 1 0 0 0 1 1h5\"/><path d=\"M8 12v-1\"/><path d=\"M8 18v-2\"/><path d=\"M8 7V6\"/><circle cx=\"8\" cy=\"20\" r=\"2\"/>",
    "file-up": "<path d=\"M6 22a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h8a2.4 2.4 0 0 1 1.704.706l3.588 3.588A2.4 2.4 0 0 1 20 8v12a2 2 0 0 1-2 2z\"/><path d=\"M14 2v5a1 1 0 0 0 1 1h5\"/><path d=\"M12 12v6\"/><path d=\"m15 15-3-3-3 3\"/>",
    "file-down": "<path d=\"M6 22a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h8a2.4 2.4 0 0 1 1.704.706l3.588 3.588A2.4 2.4 0 0 1 20 8v12a2 2 0 0 1-2 2z\"/><path d=\"M14 2v5a1 1 0 0 0 1 1h5\"/><path d=\"M12 18v-6\"/><path d=\"m9 15 3 3 3-3\"/>",
    "wrench": "<path d=\"M14.7 6.3a1 1 0 0 0 0 1.4l1.6 1.6a1 1 0 0 0 1.4 0l3.106-3.105c.32-.322.863-.22.983.218a6 6 0 0 1-8.259 7.057l-7.91 7.91a1 1 0 0 1-2.999-3l7.91-7.91a6 6 0 0 1 7.057-8.259c.438.12.54.662.219.984z\"/>",
    "lock": "<rect width=\"18\" height=\"11\" x=\"3\" y=\"11\" rx=\"2\" ry=\"2\"/><path d=\"M7 11V7a5 5 0 0 1 10 0v4\"/>",
    "eye": "<path d=\"M2.062 12.348a1 1 0 0 1 0-.696 10.75 10.75 0 0 1 19.876 0 1 1 0 0 1 0 .696 10.75 10.75 0 0 1-19.876 0\"/><circle cx=\"12\" cy=\"12\" r=\"3\"/>",
    "eye-off": "<path d=\"M10.733 5.076a10.744 10.744 0 0 1 11.205 6.575 1 1 0 0 1 0 .696 10.747 10.747 0 0 1-1.444 2.49\"/><path d=\"M14.084 14.158a3 3 0 0 1-4.242-4.242\"/><path d=\"M17.479 17.499a10.75 10.75 0 0 1-15.417-5.151 1 1 0 0 1 0-.696 10.75 10.75 0 0 1 4.446-5.143\"/><path d=\"m2 2 20 20\"/>",
    "circle-check": "<circle cx=\"12\" cy=\"12\" r=\"10\"/><path d=\"m9 12 2 2 4-4\"/>",
    "circle-alert": "<circle cx=\"12\" cy=\"12\" r=\"10\"/><line x1=\"12\" x2=\"12\" y1=\"8\" y2=\"12\"/><line x1=\"12\" x2=\"12.01\" y1=\"16\" y2=\"16\"/>",
    "triangle-alert": "<path d=\"m21.73 18-8-14a2 2 0 0 0-3.48 0l-8 14A2 2 0 0 0 4 21h16a2 2 0 0 0 1.73-3\"/><path d=\"M12 9v4\"/><path d=\"M12 17h.01\"/>",
    "info": "<circle cx=\"12\" cy=\"12\" r=\"10\"/><path d=\"M12 16v-4\"/><path d=\"M12 8h.01\"/>",
    "trash-2": "<path d=\"M10 11v6\"/><path d=\"M14 11v6\"/><path d=\"M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6\"/><path d=\"M3 6h18\"/><path d=\"M8 6V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2\"/>",
    "rotate-cw": "<path d=\"M21 12a9 9 0 1 1-9-9c2.52 0 4.93 1 6.74 2.74L21 8\"/><path d=\"M21 3v5h-5\"/>",
    "refresh-cw": "<path d=\"M3 12a9 9 0 0 1 9-9 9.75 9.75 0 0 1 6.74 2.74L21 8\"/><path d=\"M21 3v5h-5\"/><path d=\"M21 12a9 9 0 0 1-9 9 9.75 9.75 0 0 1-6.74-2.74L3 16\"/><path d=\"M8 16H3v5\"/>",
    "save": "<path d=\"M15.2 3a2 2 0 0 1 1.4.6l3.8 3.8a2 2 0 0 1 .6 1.4V19a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2z\"/><path d=\"M17 21v-7a1 1 0 0 0-1-1H8a1 1 0 0 0-1 1v7\"/><path d=\"M7 3v4a1 1 0 0 0 1 1h7\"/>",
    "scissors": "<circle cx=\"6\" cy=\"6\" r=\"3\"/><path d=\"M8.12 8.12 12 12\"/><path d=\"M20 4 8.12 15.88\"/><circle cx=\"6\" cy=\"18\" r=\"3\"/><path d=\"M14.8 14.8 20 20\"/>",
    "layers": "<path d=\"M12.83 2.18a2 2 0 0 0-1.66 0L2.6 6.08a1 1 0 0 0 0 1.83l8.58 3.91a2 2 0 0 0 1.66 0l8.58-3.9a1 1 0 0 0 0-1.83z\"/><path d=\"M2 12a1 1 0 0 0 .58.91l8.6 3.91a2 2 0 0 0 1.65 0l8.58-3.9A1 1 0 0 0 22 12\"/><path d=\"M2 17a1 1 0 0 0 .58.91l8.6 3.91a2 2 0 0 0 1.65 0l8.58-3.9A1 1 0 0 0 22 17\"/>",
    "sliders-horizontal": "<path d=\"M10 5H3\"/><path d=\"M12 19H3\"/><path d=\"M14 3v4\"/><path d=\"M16 17v4\"/><path d=\"M21 12h-9\"/><path d=\"M21 19h-5\"/><path d=\"M21 5h-7\"/><path d=\"M8 10v4\"/><path d=\"M8 12H3\"/>",
    "arrow-left": "<path d=\"m12 19-7-7 7-7\"/><path d=\"M19 12H5\"/>",
    "chevron-left": "<path d=\"m15 18-6-6 6-6\"/>",
    "chevron-right": "<path d=\"m9 18 6-6-6-6\"/>",
    "chevron-down": "<path d=\"m6 9 6 6 6-6\"/>",
    "undo-2": "<path d=\"M9 14 4 9l5-5\"/><path d=\"M4 9h10.5a5.5 5.5 0 0 1 5.5 5.5a5.5 5.5 0 0 1-5.5 5.5H11\"/>",
    "redo-2": "<path d=\"m15 14 5-5-5-5\"/><path d=\"M20 9H9.5A5.5 5.5 0 0 0 4 14.5A5.5 5.5 0 0 0 9.5 20H13\"/>",
    "zoom-in": "<circle cx=\"11\" cy=\"11\" r=\"8\"/><line x1=\"21\" x2=\"16.65\" y1=\"21\" y2=\"16.65\"/><line x1=\"11\" x2=\"11\" y1=\"8\" y2=\"14\"/><line x1=\"8\" x2=\"14\" y1=\"11\" y2=\"11\"/>",
    "zoom-out": "<circle cx=\"11\" cy=\"11\" r=\"8\"/><line x1=\"21\" x2=\"16.65\" y1=\"21\" y2=\"16.65\"/><line x1=\"8\" x2=\"14\" y1=\"11\" y2=\"11\"/>",
    "maximize": "<path d=\"M8 3H5a2 2 0 0 0-2 2v3\"/><path d=\"M21 8V5a2 2 0 0 0-2-2h-3\"/><path d=\"M3 16v3a2 2 0 0 0 2 2h3\"/><path d=\"M16 21h3a2 2 0 0 0 2-2v-3\"/>",
    "brush": "<path d=\"m11 10 3 3\"/><path d=\"M6.5 21A3.5 3.5 0 1 0 3 17.5a2.62 2.62 0 0 1-.708 1.792A1 1 0 0 0 3 21z\"/><path d=\"M9.969 17.031 21.378 5.624a1 1 0 0 0-3.002-3.002L6.967 14.031\"/>",
    "sparkles": "<path d=\"M11.017 2.814a1 1 0 0 1 1.966 0l1.051 5.558a2 2 0 0 0 1.594 1.594l5.558 1.051a1 1 0 0 1 0 1.966l-5.558 1.051a2 2 0 0 0-1.594 1.594l-1.051 5.558a1 1 0 0 1-1.966 0l-1.051-5.558a2 2 0 0 0-1.594-1.594l-5.558-1.051a1 1 0 0 1 0-1.966l5.558-1.051a2 2 0 0 0 1.594-1.594z\"/><path d=\"M20 2v4\"/><path d=\"M22 4h-4\"/><circle cx=\"4\" cy=\"20\" r=\"2\"/>",
    "eraser": "<path d=\"M21 21H8a2 2 0 0 1-1.42-.587l-3.994-3.999a2 2 0 0 1 0-2.828l10-10a2 2 0 0 1 2.829 0l5.999 6a2 2 0 0 1 0 2.828L12.834 21\"/><path d=\"m5.082 11.09 8.828 8.828\"/>",
    "wand-sparkles": "<path d=\"m21.64 3.64-1.28-1.28a1.21 1.21 0 0 0-1.72 0L2.36 18.64a1.21 1.21 0 0 0 0 1.72l1.28 1.28a1.2 1.2 0 0 0 1.72 0L21.64 5.36a1.2 1.2 0 0 0 0-1.72\"/><path d=\"m14 7 3 3\"/><path d=\"M5 6v4\"/><path d=\"M19 14v4\"/><path d=\"M10 2v2\"/><path d=\"M7 8H3\"/><path d=\"M21 16h-4\"/><path d=\"M11 3H9\"/>",
    "app-window": "<rect x=\"2\" y=\"4\" width=\"20\" height=\"16\" rx=\"2\"/><path d=\"M10 4v4\"/><path d=\"M2 8h20\"/><path d=\"M6 4v4\"/>",
    "camera": "<path d=\"M13.997 4a2 2 0 0 1 1.76 1.05l.486.9A2 2 0 0 0 18.003 7H20a2 2 0 0 1 2 2v9a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V9a2 2 0 0 1 2-2h1.997a2 2 0 0 0 1.759-1.048l.489-.904A2 2 0 0 1 10.004 4z\"/><circle cx=\"12\" cy=\"13\" r=\"3\"/>",
    "crop": "<path d=\"M6 2v14a2 2 0 0 0 2 2h14\"/><path d=\"M18 22V8a2 2 0 0 0-2-2H2\"/>",
    "rotate-ccw": "<path d=\"M3 12a9 9 0 1 0 9-9 9.75 9.75 0 0 0-6.74 2.74L3 8\"/><path d=\"M3 3v5h5\"/>",
    "share": "<path d=\"M12 2v13\"/><path d=\"m16 6-4-4-4 4\"/><path d=\"M4 12v8a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2v-8\"/>",
    "send": "<path d=\"M14.536 21.686a.5.5 0 0 0 .937-.024l6.5-19a.496.496 0 0 0-.635-.635l-19 6.5a.5.5 0 0 0-.024.937l7.93 3.18a2 2 0 0 1 1.112 1.11z\"/><path d=\"m21.854 2.147-10.94 10.939\"/>",
    "scan-line": "<path d=\"M3 7V5a2 2 0 0 1 2-2h2\"/><path d=\"M17 3h2a2 2 0 0 1 2 2v2\"/><path d=\"M21 17v2a2 2 0 0 1-2 2h-2\"/><path d=\"M7 21H5a2 2 0 0 1-2-2v-2\"/><path d=\"M7 12h10\"/>",
    "ellipsis": "<circle cx=\"12\" cy=\"12\" r=\"1\"/><circle cx=\"19\" cy=\"12\" r=\"1\"/><circle cx=\"5\" cy=\"12\" r=\"1\"/>",
    "arrow-up-down": "<path d=\"m21 16-4 4-4-4\"/><path d=\"M17 20V4\"/><path d=\"m3 8 4-4 4 4\"/><path d=\"M7 4v16\"/>",
    "zap": "<path d=\"M4 14a1 1 0 0 1-.78-1.63l9.9-10.2a.5.5 0 0 1 .86.46l-1.92 6.02A1 1 0 0 0 13 10h7a1 1 0 0 1 .78 1.63l-9.9 10.2a.5.5 0 0 1-.86-.46l1.92-6.02A1 1 0 0 0 11 14z\"/>",
    "aperture": "<circle cx=\"12\" cy=\"12\" r=\"10\"/><path d=\"m14.31 8 5.74 9.94\"/><path d=\"M9.69 8h11.48\"/><path d=\"m7.38 12 5.74-9.94\"/><path d=\"M9.69 16 3.95 6.06\"/><path d=\"M14.31 16H2.83\"/><path d=\"m16.62 12-5.74 9.94\"/>",
    "pencil": "<path d=\"M21.174 6.812a1 1 0 0 0-3.986-3.987L3.842 16.174a2 2 0 0 0-.5.83l-1.321 4.352a.5.5 0 0 0 .623.622l4.353-1.32a2 2 0 0 0 .83-.497z\"/><path d=\"m15 5 4 4\"/>"
  };
  /* @icons:end */

  const BRAND = '6ThSense';

  /* The 6ThSense tool suite. Current app links to "/", the others to their local ports. */
  const APPS = [
    { id: 'pdf', name: 'แปลง PDF', icon: 'file-text', url: 'http://127.0.0.1:8000/' },
    { id: 'webp', name: 'รูปเป็น WebP', icon: 'images', url: 'http://localhost:5173/' },
    { id: 'ico', name: 'รูปเป็น ICO', icon: 'app-window', url: 'http://localhost:5174/' },
    { id: 'removebg', name: 'ลบพื้นหลัง', icon: 'scissors', url: 'http://127.0.0.1:8765/' },
  ];

  const esc = s => String(s).replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));
  const resolve = el => (typeof el === 'string' ? document.querySelector(el) : el);

  function icon(name, opts) {
    opts = opts || {};
    const body = ICONS[name];
    if (!body) { console.warn('[DS] unknown icon: ' + name); return ''; }
    const cls = 'ds-icon' + (opts.size ? ' ds-icon--' + opts.size : '') + (opts.className ? ' ' + opts.className : '');
    return '<svg class="' + cls + '" viewBox="0 0 24 24" width="20" height="20" fill="none" stroke="currentColor" stroke-width="2"'
      + ' stroke-linecap="round" stroke-linejoin="round" aria-hidden="true" focusable="false">' + body + '</svg>';
  }

  function hydrateIcons(root) {
    (resolve(root) || document).querySelectorAll('i[data-icon]').forEach(el => {
      const html = icon(el.dataset.icon, { size: el.dataset.size, className: el.className });
      if (html) el.outerHTML = html;
    });
  }

  /* Brand mark: a "6" on a rounded square. default = navy tile, inverse = yellow tile (for navy surfaces). */
  function logo(variant) {
    const inverse = variant === 'inverse';
    const tile = inverse ? '#FFD300' : '#00264B';
    const ink = inverse ? '#00264B' : '#FFD300';
    return '<svg class="ds-brand__mark" viewBox="0 0 32 32" aria-hidden="true" focusable="false">'
      + '<rect width="32" height="32" rx="8" fill="' + tile + '"/>'
      + '<circle cx="16" cy="19.5" r="5.5" fill="none" stroke="' + ink + '" stroke-width="3"/>'
      + '<path d="M20.5 7.5C14 8 10.5 12.5 10.5 19.5" fill="none" stroke="' + ink + '" stroke-width="3" stroke-linecap="round"/>'
      + '</svg>';
  }

  function renderHeader(target, appId) {
    const el = resolve(target);
    if (!el) return;
    el.classList.add('ds-header');
    el.innerHTML =
      '<div class="ds-container ds-header__inner">'
      + '<a class="ds-brand" href="/" aria-label="' + BRAND + '">' + logo('inverse')
      + '<span class="ds-brand__name"><span>6Th</span>Sense</span></a>'
      + '<nav class="ds-nav" aria-label="เครื่องมือของ ' + BRAND + '">'
      + APPS.map(a => {
        const current = a.id === appId;
        return '<a class="ds-nav__link" href="' + (current ? '/' : a.url) + '"' + (current ? ' aria-current="page"' : '') + '>'
          + icon(a.icon) + esc(a.name) + '</a>';
      }).join('')
      + '</nav></div>';
  }

  function renderFooter(target, appId, note) {
    const el = resolve(target);
    if (!el) return;
    const app = APPS.find(a => a.id === appId);
    el.classList.add('ds-footer');
    el.innerHTML =
      '<div class="ds-container ds-footer__inner">'
      + '<span class="ds-footer__brand">' + logo() + '<span>' + BRAND + (app ? ' · ' + esc(app.name) : '') + '</span></span>'
      + '<span>' + (note ? esc(note) + ' · ' : '') + '© ' + new Date().getFullYear() + ' ' + BRAND + ' — พัฒนาโดย ' + BRAND + '</span>'
      + '</div>';
  }

  /* ---- Toast ------------------------------------------------------------- */
  const TOAST_ICONS = { success: 'circle-check', error: 'circle-alert', warning: 'triangle-alert', info: 'info' };
  let region = null;

  function toast(message, opts) {
    if (typeof opts === 'string') opts = { type: opts };
    opts = opts || {};
    const type = TOAST_ICONS[opts.type] ? opts.type : 'info';
    const duration = opts.duration != null ? opts.duration : (type === 'error' ? 6000 : 4000);

    if (!region || !region.isConnected) {
      region = document.createElement('div');
      region.className = 'ds-toast-region';
      region.setAttribute('aria-live', 'polite');
      document.body.appendChild(region);
    }
    const el = document.createElement('div');
    el.className = 'ds-toast ds-toast--' + type;
    el.setAttribute('role', type === 'error' ? 'alert' : 'status');
    el.innerHTML = icon(TOAST_ICONS[type]) + '<div class="ds-toast__msg"></div>'
      + '<button type="button" class="ds-toast__close" aria-label="ปิด">' + icon('x') + '</button>';
    el.querySelector('.ds-toast__msg').textContent = message;

    const close = () => {
      if (el.classList.contains('is-leaving')) return;
      el.classList.add('is-leaving');
      setTimeout(() => el.remove(), 200);
    };
    el.querySelector('button').addEventListener('click', close);
    region.appendChild(el);
    while (region.children.length > 3) region.firstElementChild.remove();
    if (duration > 0) setTimeout(close, duration);
    return close;
  }

  /* ---- Modal ------------------------------------------------------------- */
  const MODAL_ICONS = { primary: 'info', danger: 'triangle-alert', warning: 'triangle-alert', success: 'circle-check' };

  function dialog(opts) {
    return new Promise(done => {
      const variant = MODAL_ICONS[opts.variant] ? opts.variant : 'primary';
      const d = document.createElement('dialog');
      d.className = 'ds-modal';
      d.innerHTML =
        '<div class="ds-modal__header">'
        + '<span class="ds-modal__icon' + (variant === 'primary' ? '' : ' ds-modal__icon--' + variant) + '">' + icon(opts.icon || MODAL_ICONS[variant]) + '</span>'
        + '<h2 class="ds-modal__title"></h2></div>'
        + '<div class="ds-modal__body"></div>'
        + '<div class="ds-modal__footer">'
        + (opts.cancelText ? '<button type="button" class="ds-btn" data-result="0"></button>' : '')
        + '<button type="button" class="ds-btn ' + (variant === 'danger' ? 'ds-btn--danger' : 'ds-btn--primary') + '" data-result="1"></button>'
        + '</div>';
      d.querySelector('.ds-modal__title').textContent = opts.title || '';
      const body = d.querySelector('.ds-modal__body');
      if (opts.message) body.textContent = opts.message; else body.remove();
      const cancelBtn = d.querySelector('[data-result="0"]');
      const okBtn = d.querySelector('[data-result="1"]');
      if (cancelBtn) cancelBtn.textContent = opts.cancelText;
      okBtn.textContent = opts.confirmText;

      // Settle synchronously; the async 'close' event is only a fallback (e.g. dialog closed by other code).
      let settled = false;
      const finish = value => {
        if (settled) return;
        settled = true;
        if (d.open) d.close();
        d.remove();
        done(value);
      };
      d.addEventListener('click', e => {
        const btn = e.target.closest('[data-result]');
        if (btn) finish(btn.dataset.result === '1');
        else if (e.target === d) finish(false); // backdrop
      });
      d.addEventListener('cancel', e => { e.preventDefault(); finish(false); }); // Esc
      d.addEventListener('close', () => finish(false));
      document.body.appendChild(d);
      d.showModal();
      // Destructive actions start focused on Cancel.
      (variant === 'danger' && cancelBtn ? cancelBtn : okBtn).focus();
    });
  }

  function confirm(opts) {
    if (typeof opts === 'string') opts = { message: opts };
    return dialog(Object.assign({ title: 'ยืนยันการทำรายการ', confirmText: 'ยืนยัน', cancelText: 'ยกเลิก' }, opts));
  }

  function alert(opts) {
    if (typeof opts === 'string') opts = { message: opts };
    return dialog(Object.assign({ title: 'แจ้งเตือน', confirmText: 'ตกลง', variant: 'warning' }, opts, { cancelText: null })).then(() => undefined);
  }

  /* ---- Button loading state ---------------------------------------------- */
  function setLoading(button, loading, text) {
    const btn = resolve(button);
    if (!btn) return;
    if (loading) {
      if (!btn.dataset.dsLabel) btn.dataset.dsLabel = btn.innerHTML;
      btn.classList.add('is-loading');
      btn.disabled = true;
      btn.setAttribute('aria-busy', 'true');
      btn.innerHTML = '<span class="ds-spinner" aria-hidden="true"></span><span>' + esc(text || 'กำลังประมวลผล…') + '</span>';
    } else {
      if (btn.dataset.dsLabel != null) btn.innerHTML = btn.dataset.dsLabel;
      delete btn.dataset.dsLabel;
      btn.classList.remove('is-loading');
      btn.removeAttribute('aria-busy');
      btn.disabled = false;
    }
  }

  function formatBytes(n) {
    if (n < 1024) return n + ' B';
    if (n < 1024 * 1024) return (n / 1024).toFixed(1) + ' KB';
    return (n / 1024 / 1024).toFixed(2) + ' MB';
  }

  window.DS = {
    version: '1.0.0',
    apps: APPS,
    icon, hydrateIcons, logo,
    renderHeader, renderFooter,
    toast, confirm, alert,
    setLoading, formatBytes,
  };

  if (document.readyState === 'loading') document.addEventListener('DOMContentLoaded', () => hydrateIcons());
  else hydrateIcons();
})();
